from datetime import datetime, timezone
from uuid import uuid4
from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, JSON, Float
from sqlalchemy.orm import Mapped, mapped_column, relationship
from pgvector.sqlalchemy import Vector
from app.database.base import Base

class User(Base):
    __tablename__='users'; id:Mapped[int]=mapped_column(primary_key=True); email:Mapped[str]=mapped_column(String(255),unique=True,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc)); sessions=relationship('Session',back_populates='user',cascade='all, delete-orphan')
class Session(Base):
    __tablename__='sessions'; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); name:Mapped[str]=mapped_column(String(255),default=''); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc)); user=relationship('User',back_populates='sessions'); messages=relationship('Message',back_populates='session',cascade='all, delete-orphan'); documents=relationship('Document',back_populates='session',cascade='all, delete-orphan'); memories=relationship('Memory',back_populates='session',cascade='all, delete-orphan'); runs=relationship('AgentRun',back_populates='session',cascade='all, delete-orphan')
    def __init__(self, **kwargs):
        if 'title' in kwargs and 'name' not in kwargs: kwargs['name']=kwargs.pop('title')
        super().__init__(**kwargs)
class Message(Base):
    __tablename__='messages'; id:Mapped[int]=mapped_column(primary_key=True); session_id:Mapped[int]=mapped_column(ForeignKey('sessions.id',ondelete='CASCADE'),index=True); role:Mapped[str]=mapped_column(String(32)); content:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc)); session=relationship('Session',back_populates='messages')
class Document(Base):
    __tablename__='documents'; id:Mapped[int]=mapped_column(primary_key=True); session_id:Mapped[int]=mapped_column(ForeignKey('sessions.id',ondelete='CASCADE'),index=True); filename:Mapped[str]=mapped_column(String(255)); content_type:Mapped[str]=mapped_column(String(100)); storage_key:Mapped[str]=mapped_column(String(500),unique=True); checksum:Mapped[str]=mapped_column(String(64),index=True); size_bytes:Mapped[int]=mapped_column(Integer); status:Mapped[str]=mapped_column(String(32),default='uploaded',index=True); error:Mapped[str|None]=mapped_column(Text,nullable=True); document_metadata:Mapped[dict]=mapped_column('metadata',JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc)); session=relationship('Session',back_populates='documents'); chunks=relationship('DocumentChunk',back_populates='document',cascade='all, delete-orphan')
class DocumentChunk(Base):
    __tablename__='document_chunks'; id:Mapped[int]=mapped_column(primary_key=True); document_id:Mapped[int]=mapped_column(ForeignKey('documents.id',ondelete='CASCADE'),index=True); session_id:Mapped[int|None]=mapped_column(ForeignKey('sessions.id',ondelete='CASCADE'),index=True,nullable=True); chunk_index:Mapped[int]=mapped_column(Integer); content:Mapped[str]=mapped_column(Text); page:Mapped[int|None]=mapped_column(Integer,nullable=True); section:Mapped[str|None]=mapped_column(String(255),nullable=True); search_text:Mapped[str]=mapped_column(Text,default=''); embedding:Mapped[list[float]|None]=mapped_column(Vector(768),nullable=True); document=relationship('Document',back_populates='chunks')
class Memory(Base):
    __tablename__='memories'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid4())); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),index=True); session_id:Mapped[int|None]=mapped_column(ForeignKey('sessions.id',ondelete='CASCADE'),index=True,nullable=True); content:Mapped[str]=mapped_column(Text); importance:Mapped[float]=mapped_column(Float,default=.5); embedding:Mapped[list[float]|None]=mapped_column(Vector(768),nullable=True); metadata_json:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc)); session=relationship('Session',back_populates='memories')
class AgentRun(Base):
    __tablename__='agent_runs'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid4())); session_id:Mapped[int]=mapped_column(ForeignKey('sessions.id',ondelete='CASCADE'),index=True); request_id:Mapped[str]=mapped_column(String(64),index=True); status:Mapped[str]=mapped_column(String(32),default='running'); model:Mapped[str]=mapped_column(String(100)); steps:Mapped[int]=mapped_column(Integer,default=0); tool_calls_count:Mapped[int]=mapped_column(Integer,default=0); input_tokens:Mapped[int]=mapped_column(Integer,default=0); output_tokens:Mapped[int]=mapped_column(Integer,default=0); cost:Mapped[float]=mapped_column(Float,default=0.0); error:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc)); session=relationship('Session',back_populates='runs'); tool_calls=relationship('ToolCall',back_populates='run',cascade='all, delete-orphan')
class ToolCall(Base):
    __tablename__='tool_calls'; id:Mapped[int]=mapped_column(primary_key=True); run_id:Mapped[str]=mapped_column(ForeignKey('agent_runs.id',ondelete='CASCADE'),index=True); name:Mapped[str]=mapped_column(String(100)); arguments:Mapped[dict]=mapped_column(JSON,default=dict); status:Mapped[str]=mapped_column(String(32)); latency_ms:Mapped[float]=mapped_column(Float,default=0); error:Mapped[str|None]=mapped_column(Text,nullable=True); run=relationship('AgentRun',back_populates='tool_calls')
class Job(Base):
    __tablename__='jobs'; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=lambda:str(uuid4())); type:Mapped[str]=mapped_column(String(64)); status:Mapped[str]=mapped_column(String(32),default='queued',index=True); progress:Mapped[int]=mapped_column(Integer,default=0); payload:Mapped[dict]=mapped_column(JSON,default=dict); error:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc)); started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class Evaluation(Base):
    __tablename__='evaluations'; id:Mapped[int]=mapped_column(primary_key=True); run_id:Mapped[str|None]=mapped_column(ForeignKey('agent_runs.id',ondelete='SET NULL'),nullable=True); dataset:Mapped[str]=mapped_column(String(255)); metrics:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=lambda:datetime.now(timezone.utc))
